/*************************************************************************/
/* File:        project7.c                                               */
/* Description: User project #7 - empty project directory for project    */
/*              development                                             */
/* Date:        01-2015                                                  */
/*************************************************************************/
#include <math.h>
#include <stdio.h>
#include "Xkw/Xkw.h"
#include "roger.h"
#include "simulate.h"
#include "control.h"
#include "modes.h"

// Base frame (x,y) coordinates around ball based on 
// ellipse coordinate generated by the stereo_observation(roger, obs). 
// Sent to TOUCH((roger, time, goal_angles)) method to call inv_arm_kinematics() 
// use to find angles for arm
 
// Sets the base postion (x,y,theta) 
int CHASE(roger, time, base_arm_goals) 
Robot* roger;  
double time;  
double base_arm_goals[2][3]; 
{
  Observation obs;
 
  // Sets the base and eye angles to look to the center of the ball
  SearchTrack(roger, time);  

  // Gets the position of the ball in the (x,y) plane with (obs->pos[X], obs->pos[Y])
  stereo_observation(roger, &obs);  
  
  base_arm_goals[0][0] = obs.pos[X];
  base_arm_goals[0][1] = obs.pos[Y];

  return CONVERGED;  
}

// Sets the arm angles to touch the ball
// int TOUCH(roger, time, base_arm_goals, right1_plus, right2_plus, left1_minus, left2_minus) 
int TOUCH(roger, time, base_arm_goals)
Robot* roger;   
double time;  
double base_arm_goals[2][3]; 
// double right1_plus, right2_plus, left1_minus, left2_minus; 
{ 
  double ul; 
  double ur;  
  double eu_distance;  
  int touching = FALSE;   
  // int hold = TRUE;    
  
  eu_distance = pow((pow(base_arm_goals[0][0] - roger->base_position[X],2) + pow(base_arm_goals[0][1] - roger->base_position[Y],2)), 0.5);
 
  // print part b plot
  // printf("%lf,%lf\n", time, eu_distance); 
   
  if(average_red_pixel(roger, &ul, &ur) == TRUE && eu_distance <= 0.8) { 

    // inv_arm_kinematics(roger, 0, base_arm_goals[0][0], base_arm_goals[0][1], hold, right1_plus, right2_plus, &left1_minus, &left2_minus); 
    // inv_arm_kinematics(roger, 1, base_arm_goals[0][0], base_arm_goals[0][1], hold, &right1_plus, &right2_plus, left1_minus, left2_minus);
    inv_arm_kinematics(roger, 0, base_arm_goals[0][0], base_arm_goals[0][1]);
    inv_arm_kinematics(roger, 1, base_arm_goals[0][0], base_arm_goals[0][1]); 
    
  // print part c plot    
    // Get theta1plus or minus and theta2plus or minus
    // Call fwd_kin method and x and y
    // Add x and y to current robot base x and y
    // Calculate eu_distance = pow((pow(base_arm_goals[0][0] - new_armX_position,2) + pow(base_arm_goals[0][1] - new_armY_position,2)), 0.5);
    // printf("%lf,%lf\n", time, eu_distance); 

    // if(touching == TRUE) return CONVERGED;  

    if(roger->ext_force[0][0] != 0.0 || roger->ext_force[0][1] != 0.0 || roger->ext_force[1][0] != 0.0 || roger->ext_force[1][1] != 0.0) {
      return CONVERGED; 
    } 
  
    return TRANSIENT; 
  } 
  
  return NO_REFERENCE;
}   
 
void CHASETOUCH(roger, time)
Robot* roger;
double time;
{  
  // double internal_state[2], base_arm_goals[2][3], right1_plus, right2_plus, left1_minus, left2_minus;
  double internal_state[2], base_arm_goals[2][3];
  internal_state[0] = CHASE(roger, time, base_arm_goals); // assigns values to recommended_setpoints[0]
  // internal_state[1] = TOUCH(roger, time, base_arm_goals, right1_plus, right2_plus, left1_minus, left2_minus); // assigns values to recommended_setpoints[1]
  internal_state[1] = TOUCH(roger, time, base_arm_goals);
  // for N=2
  int state, return_state;
  state = internal_state[1]*3 + internal_state[0];  
  switch (state) {
                                                             // TOUCH          CHASE
    case 0:                                                  // NO_REFERENCE - NO_REFERENCE
    case 1:                                                  // NO_REFERENCE -  TRANSIENT
    case 2:                                                  // NO_REFERENCE -  CONVERGED
      return_state = TRANSIENT; 
      roger->base_setpoint[X] = base_arm_goals[0][0] - 0.4; 
      roger->base_setpoint[Y] = base_arm_goals[0][1] - 0.4; 
      // Left arm 
      roger->arm_setpoint[0][0] = 3.14; 
      roger->arm_setpoint[0][1] = -3.10;  
      // Right arm 
      roger->arm_setpoint[1][0] = -3.14; 
      roger->arm_setpoint[1][1] = 3.10; 
      break; 
    case 3:                                                  //  TRANSIENT   - NO_REFERENCE
    case 4:                                                  //  TRANSIENT   -  TRANSIENT
    case 5:                                                  //  TRANSIENT   -  CONVERGED
      return_state = TRANSIENT;
      roger->base_setpoint[X] = base_arm_goals[0][0] - 0.4;
      roger->base_setpoint[Y] = base_arm_goals[0][1] - 0.4; 
      // roger->arm_setpoint[1][0] = right1_plus; 
      // roger->arm_setpoint[1][1] = right2_plus; 
      // roger->arm_setpoint[0][0] = left1_minus;
      // roger->arm_setpoint[0][1] = left2_minus; 
      break;
    case 6:                                                  //  CONVERGED   - NO_REFERENCE
    case 7:                                                  //  CONVERGED   -  TRANSIENT
    case 8:                                                  //  CONVERGED   -  CONVERGED
      return_state = CONVERGED;
      roger->base_setpoint[X] = base_arm_goals[0][0] - 0.4;
      roger->base_setpoint[Y] = base_arm_goals[0][1] - 0.4;
      // roger->arm_setpoint[1][0] = right1_plus;
      // roger->arm_setpoint[1][1] = right2_plus;
      // roger->arm_setpoint[0][0] = left1_minus; 
      // roger->arm_setpoint[0][1] = left2_minus;
      break; 
    default: 
      break;  
  }
} 

void project7_control(roger, time)
Robot* roger;
double time;
{ 
  CHASETOUCH(roger, time);
}

/************************************************************************/
void project7_reset(roger)
Robot* roger;
{ }

// prompt for and read user customized input values
void project7_enter_params() 
{
  printf("Project 7 enter_params called. \n");
}

//function called when the 'visualize' button on the gui is pressed
void project7_visualize(roger)
Robot* roger;
{ }