/*************************************************************************/
/* File:        project4.c                                               */
/* Description: User project #4 - empty project directory for project    */
/*              developement                                             */
/* Date:        01-2015                                                  */
/*************************************************************************/
#include <math.h>
#include <stdio.h>
#include "Xkw/Xkw.h"
#include "roger.h"
#include "simulate.h"
#include "control.h"
#include "modes.h"

int continue_search = TRUE; 

int SEARCH(roger, time, goal_angles) 
Robot* roger;  
double time;  
double goal_angles[2][3];
{  
  // Random angle generated by sample_gaze_direction() method
  double heading; 
  //roger->base_setpoint[THETA] = heading;  

  if(continue_search == TRUE) {
    // If method does not produce desired random angle then return NO_REFERENCE
    if(sample_gaze_direction(&heading) == FALSE) {
      return NO_REFERENCE;  
    }
    else {
      // Set eye angles to the random heading angle so it search around
      // a lot in a wide range to increase the chances of finding the ball 
      goal_angles[0][0] = heading;  
      goal_angles[0][1] = heading; 
      // Set base angle to the random heading angle 
      goal_angles[0][2] = heading; 
       
      // Checks to see whether the random angle is visible by Roger 
      // Roger's eyes can go to a max range of -pi/2 to pi/2 so you check if 
      // the angle is within the range by adding and subtracting 90 degress the base angle.
      // If angle is within Roger's view, then it is considered CONVERGED
      if((heading >= roger->base_position[THETA] - M_PI/2) && (heading <= roger->base_position[THETA] + M_PI/2)) {
        return CONVERGED;   
      }   
    }
  } 
} 

int TRACK(roger, time, goal_angles)
Robot* roger;
double time;
double goal_angles[2][3];
{ 
  // Starting lines are Project 3 code for setting eye angles to look at the center of the ball
  double ul = 0.0;  
  double ur = 0.0;

  double oc_left_error = 0.0;
  double oc_right_error = 0.0;

  double base_control_error; 
      
  if(average_red_pixel(roger, &ul, &ur)) { 
    
    oc_left_error = atan2((double) (ul-63), (double) FOCAL_LENGTH);
    oc_right_error = atan2((double) (ur-63), (double) FOCAL_LENGTH);   
 
    // Calculations are made to see to what angle the eyes 
    // should at to point to the center of the red ball 
    goal_angles[1][0] = roger->eye_theta[0] + oc_left_error; 
    goal_angles[1][1] = roger->eye_theta[1] + oc_right_error;

    // Set the new base angle to the average of the left and right eye angles and add to the current base angle 
    goal_angles[1][2] = (goal_angles[1][0] + goal_angles[1][1]) / 2.0 + roger->base_position[THETA];
    // Do not continue search since ball is located by Roger
    continue_search = FALSE;  
     
    // Calcuate base control error
    base_control_error = roger->base_setpoint[THETA] - roger->base_position[THETA];
    // printf("%lf,%lf\n", time, base_control_error);  

    // Return CONVERGED when both eyes look at center of the red ball and when base is rotated to face ball 
    // which results in both eye angles canceling out and having a sum of 0
    if(goal_angles[1][0] + goal_angles[1][1] == 0) return CONVERGED; 

    // Otherwise returns TRANSIENT otherwise if still in progress to reach center of ball
    return TRANSIENT; 
  } 
  
  // If both eyes don't detect the red ball then return NO_REFERENCE
  // Continue search since Roger did not find ball in its eyesight 
  continue_search = TRUE; 
  return NO_REFERENCE;
  
}  

void SearchTrack(roger, time)
Robot* roger;
double time;
{ 
  double internal_state[2], goal_angles[2][3];
  internal_state[0] = SEARCH(roger, time, goal_angles); // assigns values to recommended_setpoints[0]
  internal_state[1] = TRACK(roger, time, goal_angles); // assigns values to recommended_setpoints[1]
  // for N=2
  int state, return_state;
  state = internal_state[1]*3 + internal_state[0];
  switch (state) {
                                                             // TRACK          SEARCH
    case 0:                                                  // NO_REFERENCE - NO_REFERENCE
      // choose action[i] 0 ,= i ,= NACTIONS                 
      // submit_setpoints(recommended_setpoints[i]); 
    case 1:                                                  // NO_REFERENCE -  TRANSIENT
    case 2:                                                  // NO_REFERENCE -  CONVERGED
      // If ball is not seen by Roger keep setting roger base and
      // eye angles to the random angles generated by the
      // sample_gaze_direction method in hopes to find the ball
      return_state = TRANSIENT;
      roger->eyes_setpoint[0] = goal_angles[0][0]; 
      roger->eyes_setpoint[1] = goal_angles[0][1]; 
      roger->base_setpoint[THETA] = goal_angles[0][2];  
      break;
    case 3:                                                  //  TRANSIENT   - NO_REFERENCE
    case 4:                                                  //  TRANSIENT   -  TRANSIENT
    case 5:                                                  //  TRANSIENT   -  CONVERGED
      return_state = TRANSIENT;
      roger->eyes_setpoint[0] = goal_angles[1][0];
      roger->eyes_setpoint[1] = goal_angles[1][1];
      roger->base_setpoint[THETA] = goal_angles[1][2];
      break;
    case 6:                                                  //  CONVERGED   - NO_REFERENCE
    case 7:                                                  //  CONVERGED   -  TRANSIENT
    case 8:                                                  //  CONVERGED   -  CONVERGED
      return_state = CONVERGED; 
      roger->eyes_setpoint[0] = goal_angles[1][0]; 
      roger->eyes_setpoint[1] = goal_angles[1][1]; 
      roger->base_setpoint[THETA] = goal_angles[1][2];    
      break; 
    default: 
      break; 
  }
}

void project4_control(roger, time)
Robot* roger;
double time;
{ 
  SearchTrack(roger, time);
   
}

/************************************************************************/
void project4_reset(roger)
Robot* roger;
{ }

// prompt for and read user customized input values
void project4_enter_params() 
{
  printf("Project 4 enter_params called. \n");
}

//function called when the 'visualize' button on the gui is pressed
void project4_visualize(roger)
Robot* roger;
{ }
